import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home({users}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <useAllPosts />
      <div className="container"> 
        <Link href="/posts/first-post">
          <a>最初の投稿ページにアクセスします</a>
        </Link>
        <br />
        <br />
        <Link href="/firebase">
          <a>firebase投稿一覧へ</a>
        </Link>
      </div>
      <div>
        <h1>ユーザー一覧</h1>
        <ul>
          {users.map((user) => {
            return (
              <div>
                <Link href={`/users/${user.id}`}>
                  <a><li key={user.id}>{user.name}</li></a>
                </Link>
                <li>{user.email}</li>
              </div>
            );
          })}
        </ul>
      </div>
    </div>
  )
}

  export async function getServerSideProps() {
    const res = await fetch(`https://jsonplaceholder.typicode.com/users`);
    const users = await res.json();
    return { props: { users } };
}
